### ISSUE TITLE
Provide a usage licence

### ISSUE THREAD

**Issue by abeMedia** [mysteriumnetwork/go-openvpn#54]
For any organisation to use this a license is required. Could you provide one please?
May I suggest GPLv3? :wink:

**Comment by BamButz** [comment]
I would go so far and say everyone needs the license information to be legally secure.

**Comment by Waldz** [comment]
Thanks for voting.
We will probably add GPLv3 as for all our libraries, see example here https://github.com/mysteriumnetwork/node/blob/master/LICENSE

**Comment by Waldz** [comment]
We decided to license under same terms as Openvpn itself, and it is https://github.com/OpenVPN/openvpn3
