### ISSUE TITLE
Does go-openvpn support using a separate certificate authority?

### ISSUE THREAD

**Issue by apache8080** [mysteriumnetwork/go-openvpn#58]
I have a certificate authority running on a separate server and want to use that to sign the server certs and the client certs. Is there a way to do that with go-openvpn? Also I am following a setup that is similar to [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04)

**Comment by zolia** [comment]
Hello, 

there is no such functionality atm. This project is used as a part for our https://github.com/mysteriumnetwork/node effort. It generates certificate on the fly for each connecting session. There is no centralized place for certificate management as this is used for decentralized project 

It should not be hard to extend to support centralized cert repo, but we would like to keep this lib as slim as possible with minimal changes.
