### ISSUE TITLE
nonpriv-ip command not found issue when starting opevpn server

### ISSUE THREAD

**Issue by apache8080** [mysteriumnetwork/go-openvpn#59]
I am starting an openvpn server using this library and I get the following error:
```
Linux ip link set failed: could not execute external program
```
This is most likely being caused because of this line of code:
[https://github.com/mysteriumnetwork/go-openvpn/blob/12f29231871167a376c59b9cbc93e84a60e22e39/openvpn/tunnel/setup_tun_linux.go#L53](https://github.com/mysteriumnetwork/go-openvpn/blob/12f29231871167a376c59b9cbc93e84a60e22e39/openvpn/tunnel/setup_tun_linux.go#L53)
nonpriv-ip doesn't exist anywhere and so the command errors out. How do I fix this issue?

**Comment by zolia** [comment]
nonpriv-ip has to be on the path for openvpn to find. OpenVPN requires a single executable for route management. This file is used to manage routes in non-privileged mode. Its contents could be: 
```
#!/bin/sh
sudo /sbin/ip $*
```
